global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
      - names:
          - "prometheus"
        type: 'A'
        port: 9090
  - job_name: 'django'
    scrape_interval: 5s
    metrics_path: '/stats/metrics'
    dns_sd_configs:
      - names:
          - 'tasks.backend'
          - 'backend'
        type: 'A'
        port: 8000
  - job_name: cadvisor
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
          - 'cadvisor'
        type: 'A'
        port: 8080
  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
          - 'node-exporter'
        type: 'A'
        port: 9100
