# Generated by Django 2.1.7 on 2019-03-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('registration', '0001_initial'), ('registration', '0002_auto_20190313_1512'), ('registration', '0003_auto_20190313_1520'), ('registration', '0004_auto_20190313_1527'), ('registration', '0005_auto_20190313_1548'), ('registration', '0006_paymentmodel_notes'), ('registration', '0007_auto_20190313_1611'), ('registration', '0008_registrationmodel_notes'), ('registration', '0009_registrationmodel_membership_level'), ('registration', '0010_auto_20190318_1435'), ('registration', '0011_auto_20190318_1451')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('con_start_time', models.DateTimeField()),
                ('con_reg_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_registered', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationAddinModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ConventionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.ConventionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notes', models.TextField(blank=True, null=True)),
                ('membership_level', models.SmallIntegerField(choices=[(0, 'Attendee'), (1, 'Staff'), (2, 'Helper'), (3, 'Organisation'), (4, 'Director')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registrationaddinmodel',
            name='registrations_added_to',
            field=models.ManyToManyField(blank=True, related_name='addons', to='registration.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registration.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registrationmodel',
            unique_together={('user', 'convention')},
        ),
        migrations.RenameField(
            model_name='conventionmodel',
            old_name='con_reg_time',
            new_name='con_reg_close_time',
        ),
        migrations.RenameField(
            model_name='conventionmodel',
            old_name='con_start_time',
            new_name='con_reg_start_time',
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='con_event_close_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='con_event_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
