# Generated by Django 2.1.7 on 2019-03-27 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('con_event_start_date', models.DateField()),
                ('con_event_close_date', models.DateField()),
                ('con_reg_start_time', models.DateTimeField()),
                ('con_reg_close_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_public', models.BooleanField(default=False)),
                ('uses_hotel_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Convention',
            },
        ),
        migrations.CreateModel(
            name='RegistrationAddinModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ConventionModel')),
            ],
            options={
                'verbose_name': 'Registration Add-In',
                'verbose_name_plural': 'Registration Add-Ins',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('registrations.addins'), models.Model),
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('membership_level', models.SmallIntegerField(choices=[(0, 'Attendee'), (1, 'Staff'), (2, 'Helper'), (3, 'Organisation'), (4, 'Director')], default=0)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.ConventionModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('registrations.registration'), models.Model),
        ),
        migrations.AddField(
            model_name='registrationaddinmodel',
            name='registrations_added_to',
            field=models.ManyToManyField(blank=True, related_name='addons', to='registration.RegistrationModel'),
        ),
    ]
