# Generated by Django 2.1.7 on 2019-03-26 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_squashed_0011_auto_20190318_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'regular'), (2, 'deluxe'), (3, 'junior suite'), (4, 'suite'), (5, 'penthouse')])),
                ('capacity', models.CharField(choices=[('B', 'Single bed'), ('BB', 'Double bed'), ('B B', 'Two single beds'), ('BB B', 'Double and Single bed'), ('BB BB', 'Two double beds')], max_length=6)),
                ('capacity_extra', models.PositiveSmallIntegerField(default=0, help_text='Extra capacity that can possibly be added to the room')),
                ('is_locked', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='registration.HotelModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='uses_hotel_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='conventions',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='registration.ConventionModel'),
        ),
    ]
