# Generated by Django 2.1.7 on 2019-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrationmodel',
            index=models.Index(fields=['id', 'user'], name='registratio_id_4fc534_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationmodel',
            index=models.Index(fields=['id'], name='registratio_id_b7f217_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationmodel',
            index=models.Index(fields=['user'], name='registratio_user_id_eb36bd_idx'),
        ),
    ]
