# Generated by Django 2.1.7 on 2019-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190313_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationaddinmodel',
            name='registrations_added_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='addons', to='registration.RegistrationModel'),
        ),
    ]
