# Generated by Django 2.1.7 on 2019-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190326_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conventionmodel',
            options={'verbose_name': 'Convention'},
        ),
        migrations.AlterModelOptions(
            name='hotelmodel',
            options={'verbose_name': 'Hotel'},
        ),
        migrations.AlterModelOptions(
            name='paymentmodel',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='registrationaddinmodel',
            options={'verbose_name': 'Registration Add-In', 'verbose_name_plural': 'Registration Add-Ins'},
        ),
        migrations.AlterModelOptions(
            name='registrationmodel',
            options={'verbose_name': 'Registration'},
        ),
        migrations.AlterModelOptions(
            name='roommodel',
            options={'verbose_name': 'Room'},
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='registrationmodel',
            unique_together=set(),
        ),
    ]
