# Generated by Django 2.1.7 on 2019-03-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190313_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='convention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.ConventionModel'),
        ),
    ]
