# Generated by Django 2.1.7 on 2019-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190313_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
