# Generated by Django 2.1.7 on 2019-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_paymentmodel_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
