# Generated by Django 2.1.7 on 2019-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_registrationmodel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='membership_level',
            field=models.SmallIntegerField(choices=[(0, 'Attendee'), (1, 'Staff'), (2, 'Helper'), (3, 'Organisation'), (4, 'Director')], default=0),
        ),
    ]
