# Generated by Django 2.1.7 on 2019-03-18 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0009_registrationmodel_membership_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationmodel',
            unique_together={('user', 'convention')},
        ),
    ]
