# Generated by Django 2.1.7 on 2019-03-18 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190318_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conventionmodel',
            old_name='con_reg_time',
            new_name='con_reg_close_time',
        ),
        migrations.RenameField(
            model_name='conventionmodel',
            old_name='con_start_time',
            new_name='con_reg_start_time',
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='con_event_close_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conventionmodel',
            name='con_event_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
