# Generated by Django 2.1.7 on 2019-03-27 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Floor',
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('conventions', models.ManyToManyField(blank=True, related_name='hotels', to='registration.ConventionModel')),
            ],
            options={
                'verbose_name': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'regular'), (2, 'deluxe'), (3, 'junior suite'), (4, 'suite'), (5, 'penthouse')])),
                ('capacity', models.CharField(choices=[('B', 'Single bed'), ('BB', 'Double bed'), ('B B', 'Two single beds'), ('BB B', 'Double and Single bed'), ('BB BB', 'Two double beds')], max_length=6)),
                ('capacity_extra', models.PositiveSmallIntegerField(default=0, help_text='Extra capacity that can possibly be added to the room')),
                ('is_locked', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=25, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.FloorModel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.HotelModel')),
            ],
            options={
                'verbose_name': 'Room',
            },
        ),
        migrations.CreateModel(
            name='RoomReservationModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_extra_capacity', models.BooleanField(default=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='registration.RegistrationModel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.RoomModel')),
            ],
            options={
                'verbose_name': 'Room Reservation',
            },
        ),
    ]
