apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: PostgresQL

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
  - name: PostgresQL
    type: postgres
    access: proxy
    url: http://db:5432
    user: postgres
    database: postgres
    version: 1
    sslMode: disable
    editable: true
